### ISSUE TITLE
What is internalPubkey?

### ISSUE THREAD

**Issue by nguyenHoang32** [babylonchain/btc-staking-ts#20]
In library. I found the code 
`var key = '0250929b74c1a04954b78b4b6035e97a5e078a5a0f28ec96d547bfee9ace803ac0';
var internalPubkey = Buffer.from(key, 'hex').subarray(1, 33);` It used for creating p2tr payments. 
I don't know what it is. Can someone explain for me? Thanks

**Comment by 0xted97** [comment]
I'm also stuck here, Do you understand what is it? Please explain for me
